security:
    enable_authenticator_manager: true

    password_hashers:
        App\Domain\User\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            id: App\Infrastructure\Auth\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Infrastructure\Auth\Security\JwtAuthenticator

        main:
            lazy: true
            provider: app_user_provider
            form_login: false
            logout: false

    access_control:
        # API publique
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/refresh, roles: PUBLIC_ACCESS }

        # IA API (protégée par JWT)
        - { path: ^/api/ia, roles: ROLE_USER }

        # Autres zones protégées
        - { path: ^/documents, roles: ROLE_USER }
        - { path: ^/notifications, roles: ROLE_USER }
        - { path: ^/ia, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/settings, roles: ROLE_USER }
