<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260214194540 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE Company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, sector VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE IaPromptTemplate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, prompt TEXT NOT NULL, category VARCHAR(80) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE PartnerAction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actionType VARCHAR(100) NOT NULL, parameters JSON DEFAULT NULL, result JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, executedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, partnerConnector_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A1A82A842F7880D ON PartnerAction (partnerConnector_id)');
        $this->addSql('CREATE TABLE PartnerApp (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, category VARCHAR(100) NOT NULL, apiBaseUrl VARCHAR(255) DEFAULT NULL, documentationUrl VARCHAR(255) DEFAULT NULL, isActive BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE PartnerConnector (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token TEXT DEFAULT NULL, settings JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, partnerApp_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC437F6AA76ED395 ON PartnerConnector (user_id)');
        $this->addSql('CREATE INDEX IDX_CC437F6AE72F64E2 ON PartnerConnector (partnerApp_id)');
        $this->addSql('CREATE TABLE Project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, budget NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(50) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00EE9727E3C61F9 ON Project (owner_id)');
        $this->addSql('CREATE TABLE Skill (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, category VARCHAR(50) DEFAULT NULL, level VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE Transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(10) NOT NULL, status VARCHAR(50) NOT NULL, transactionType VARCHAR(50) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ai_interaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, interactionType VARCHAR(50) NOT NULL, prompt TEXT NOT NULL, response TEXT NOT NULL, model VARCHAR(100) NOT NULL, tokensUsed INT DEFAULT NULL, metadata JSON DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BEA4E18A76ED395 ON ai_interaction (user_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN NOT NULL, sender_id INT NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FE92F8F78 ON message (recipient_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, actionUrl VARCHAR(500) DEFAULT NULL, isRead BOOLEAN NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, readAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON DEFAULT NULL, recipient_id INT NOT NULL, sender_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAE92F8F78 ON notification (recipient_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAF624B39D ON notification (sender_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, user_type VARCHAR(50) NOT NULL, genre VARCHAR(20) DEFAULT NULL, situation_familiale VARCHAR(50) DEFAULT NULL, date_naissance DATE DEFAULT NULL, pays_residence VARCHAR(100) DEFAULT NULL, nationalite VARCHAR(100) DEFAULT NULL, ville_actuelle VARCHAR(100) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, niveau_etudes VARCHAR(100) DEFAULT NULL, domaine_expertise VARCHAR(255) DEFAULT NULL, langues_parlees VARCHAR(255) DEFAULT NULL, certifications TEXT DEFAULT NULL, statut_emploi VARCHAR(100) DEFAULT NULL, poste_actuel VARCHAR(255) DEFAULT NULL, annees_experience INT DEFAULT NULL, secteur_activite VARCHAR(255) DEFAULT NULL, objectifs_professionnels TEXT DEFAULT NULL, ce_que_vous_savez_faire TEXT DEFAULT NULL, ce_que_vous_aimez_faire TEXT DEFAULT NULL, talent_cache VARCHAR(255) DEFAULT NULL, pret_a_se_former BOOLEAN NOT NULL, disponible_pour_missions BOOLEAN NOT NULL, recherche_emploi BOOLEAN NOT NULL, recherche_investisseurs BOOLEAN NOT NULL, recherche_partenaires BOOLEAN NOT NULL, sans_emploi BOOLEAN NOT NULL, linkedin_url VARCHAR(255) DEFAULT NULL, site_web_url VARCHAR(255) DEFAULT NULL, portfolio_url VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, domainesFormationSouhaites TEXT DEFAULT NULL, pretAVousExporter BOOLEAN NOT NULL, paysExportationPreference TEXT DEFAULT NULL, disponibilite VARCHAR(50) DEFAULT NULL, mobiliteGeographique VARCHAR(50) DEFAULT NULL, profilePicture VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE PartnerAction ADD CONSTRAINT FK_6A1A82A842F7880D FOREIGN KEY (partnerConnector_id) REFERENCES PartnerConnector (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE PartnerConnector ADD CONSTRAINT FK_CC437F6AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE PartnerConnector ADD CONSTRAINT FK_CC437F6AE72F64E2 FOREIGN KEY (partnerApp_id) REFERENCES PartnerApp (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Project ADD CONSTRAINT FK_E00EE9727E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ai_interaction ADD CONSTRAINT FK_5BEA4E18A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE PartnerAction DROP CONSTRAINT FK_6A1A82A842F7880D');
        $this->addSql('ALTER TABLE PartnerConnector DROP CONSTRAINT FK_CC437F6AA76ED395');
        $this->addSql('ALTER TABLE PartnerConnector DROP CONSTRAINT FK_CC437F6AE72F64E2');
        $this->addSql('ALTER TABLE Project DROP CONSTRAINT FK_E00EE9727E3C61F9');
        $this->addSql('ALTER TABLE ai_interaction DROP CONSTRAINT FK_5BEA4E18A76ED395');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FE92F8F78');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAF624B39D');
        $this->addSql('DROP TABLE Company');
        $this->addSql('DROP TABLE IaPromptTemplate');
        $this->addSql('DROP TABLE PartnerAction');
        $this->addSql('DROP TABLE PartnerApp');
        $this->addSql('DROP TABLE PartnerConnector');
        $this->addSql('DROP TABLE Project');
        $this->addSql('DROP TABLE Skill');
        $this->addSql('DROP TABLE Transaction');
        $this->addSql('DROP TABLE ai_interaction');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE "user"');
    }
}
